config/routes.rb
require 'sidekiq/web'
require 'moderator_constraint'

Rails.application.routes.draw do
  # mount Sidekiq::Web => '/sidekiq', :constraints => ModeratorConstraint.new

  namespace :admin do
    get 'possibly_deleted_user/:id', :to => 'users#show', as: 'possibly_deleted_user'

    resources :account_requests, path: 'account_requests/(:filter_by)' do
      member do
        put :approve
        put :deny
      end
    end
    resources :users, path: 'users/(:filter_by)', only: [:index] do
      member do
        put :delete
        put :restore
        put :unspam
        put :spam
        put :mark_all_users_with_ip_as_spam
      end
    end
    resources :comments, path: 'comments/(:filter_by)', only: [:index] do
       member do
        put :unspam
        put :spam
      end
    end
    resources :assets, path: 'assets/(:filter_by)', only: [:index] do
      member do
        put :unspam
        put :spam
        put :delete
        put :restore
      end
    end
    resources :mass_invites, param: :token
  end

  get '/get_an_account', :to => 'account_requests#new'
  resources 'account_requests', only: :create

  post '/get_an_account', :to => 'account_requests#create'
  get '/upload', :to => 'assets#new'
  post '/listens', :to => 'listens#create', as: 'register_listen'
  get '/new_album', :to => 'playlists#new'
  get '/favorites', :to => 'playlists#favorites'
  get '/login', :to => 'user_sessions#new', :as => 'login'
  get '/login/sso', :to => 'discourse_sso#sso'
  get '/logout', :to => 'user_sessions#destroy', as: 'logout', via: [:get, :post]
  get '/notifications/subscribe' => 'notifications#subscribe'
  get '/notifications/unsubscribe' => 'notifications#unsubscribe'

  get '/follow/:login' => 'following#follow', as: :follow
  get '/unfollow/:login' => 'following#unfollow', as: :unfollow

  # admin stuff
  get 'admin' => 'admin#index'
  get 'secretz' => 'admin#secretz'
  put 'toggle_theme' => 'pages#toggle_theme'

  get '404', to: "pages#four_oh_four"
  get 'raise_error', to: 'pages#raise_error'
  get '500', to: "pages#error"
  get 'error', to: "pages#error"
  get 'ok', to: "pages#ok"

  # one-off pages
  get 'events/rpmchallenge' => 'pages#rpm_challenge'
  get 'events/24houralbum' =>  'pages#twentyfour'

  resources :password_resets, :comments, :user_sessions, :groups

  get 'about/' => 'pages#about'
  get 'about/why-i-built-alonetone' => 'pages#why'
  %w(about press stats ok help privacy faq donate).each do |action|
    get "about/#{action}", to: "pages##{action}"
  end

  get 'signup', to: 'users#new'
  get '/activate/:perishable_token', to: 'users#activate'

  get 'radio' =>'assets#radio', :as => 'radio_home'
  get 'radio/:source' => 'assets#radio', :as => 'radio_source_home'
  get 'radio/:source/:items' => 'assets#radio', :as => 'radio'

  # top 40
  get  '/top/:top' => 'assets#top', :as => 'top'

  get 'comments' => 'comments#index', :as => 'all_comments'
  get 'playlists' => 'playlists#all', :as => 'all_playlists'

  put 'toggle_favorite' => 'users#toggle_favorite'

  match 'search' => 'search#index', via: [:post]
  match 'search/:query' => 'search#index', :as => 'search_query', via: [:get, :post]

  root :to => 'assets#latest'

  get '/users', to: redirect('/users/by/last_seen/1')
  resources :users

  # unless we have the /by/ in the route, we end up in conflict with the resource route
  get '/users/by/:sort/(:page)' => 'users#index', :as => 'sorted_users'

  get '/invite/:mass_invite_token', to: 'mass_invites_users#new', as: 'mass_invite'
  resources :mass_invites, param: :token, only: [] do
    resource :users, only: %i[new create show], controller: :mass_invites_users
  end

  get ':login/history' => 'listens#index', :as => 'listens'
  get ':login/comments' => 'comments#index', :as => 'user_comments'
  get '/:login/toggle-follow' => 'following#toggle_follow', as: :toggle_follow
  put '/:login/toggle-follow' => 'following#toggle_follow', as: :put_toggle_follow

  get ':id' => 'users#show', :as => "user_home" # DEPRECATED (duplicate)
  resources :users, :path => "/" do
    member do
      post :attach_pic
      get :sudo
      put :toggle_setting
    end
    resource 'profile'
    resources 'tracks', controller: :assets do
      member do
        get :share
        get :stats
      end
      collection do
        get  :latest
        post :search
        get  :mass_edit
      end
      resources :comments,  only: [:create, :destroy]
    end
    resources :favorites
    resources :playlists do
      collection do
        get :latest
        post :sort
        get :sort
      end
      member do
        post :attach_pic
        get  :remove_track
        post :set_playlist_title
        post :set_playlist_description
        post :sort_tracks
        post :add_track
      end
      resources :comments
    end
    get '/playlists/:id/:asset_id', :to => 'playlists#show', as: 'show_track_in_playlist'
  end
end

app/models/mass_invite.rb
# frozen_string_literal: true

class MassInvite < ApplicationRecord
  scope :recent, -> { order(created_at: :desc, id: :desc) }

  after_initialize :set_token, if: :new_record?

  has_many :mass_invite_signups
  has_many :users, through: :mass_invite_signups

  scope :active, -> { where(archived: false) }
  scope :archived, -> { where(archived: true) }

  validates :name, :token, presence: true

  def to_param
    token
  end

  private

  def set_token
    self.token ||= SecureRandom.alphanumeric(10)
  end
end

# == Schema Information
#
# Table name: mass_invites
#
#  id          :bigint(8)        not null, primary key
#  archived    :boolean          default(FALSE), not null
#  name        :text(65535)      not null
#  token       :string(255)      not null
#  users_count :integer          default(0), not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
# Indexes
#
#  index_mass_invites_on_token  (token) UNIQUE
#

app/controllers/admin/mass_invites_controller.rb
# frozen_string_literal: true

module Admin
  class MassInvitesController < Admin::BaseController
    def index
      @pagy, @mass_invites = pagy(filtered_mass_invites)
    end

    def new
      @mass_invite = MassInvite.new
    end

    def create
      @mass_invite = MassInvite.new(mass_invite_params)
      if @mass_invite.save
        redirect_to admin_mass_invites_url(filter_by: 'active')
      else
        render :new
      end
    end

    def update
      MassInvite.where(token: params[:token]).update_all(**mass_invite_params)
      redirect_to admin_mass_invites_url(filter_by: 'active')
    end

    private

    def mass_invite_params
      params.require(:mass_invite).permit(:name, :token, :archived)
    end

    def filtered_mass_invites
      MassInvite.recent.where(archived: params[:filter_by] == 'archived')
    end
  end
end

app/views/admin/mass_invites/_form.html.erb
<%= form_for([:admin, @mass_invite], builder: AdminFormBuilder) do |form| %>
  <%= form.field :name do %>
    <%= form.label_with_error :name %>
    <%= form.text_field :name %>
  <% end %>
  <%= form.field :token do %>
    <%= form.label_with_error :token %>
    <%= form.text_field :token %>
  <% end %>
  <ul class="actions submit">
    <li><%= form.submit 'Create mass invite' %></li>
    <li><%= link_to 'Cancel', admin_mass_invites_path %></li>
  </ul>
<% end %>

app/views/admin/mass_invites/_mass_invite.html.erb
<tr>
  <td><%= mass_invite.name %></div>
  <td><%= l(mass_invite.created_at, format: :short) %></div>
  <td><%= mass_invite.users_count %></td>
  <td><%= link_to(mass_invite.token, mass_invite_url(mass_invite)) %>
  <td>
    <% if mass_invite.archived? %>
      <%= button_to('Activate', admin_mass_invite_path(mass_invite, mass_invite: { archived: 0 }), method: :patch) %>
    <% else %>
      <%= button_to('Archive', admin_mass_invite_path(mass_invite, mass_invite: { archived: 1 }), method: :patch) %>
    <% end %>
  </td>
</tr

app/views/admin/mass_invites/index.html.erb
<div id="admin_columns">
  <div class="admin_column_left box">
    <h2>Admin</h2>
    <%= render partial: 'admin/navigation' %>
  </div>
  <div class="admin_column_right">
    <%= button_to 'New mass invite', new_admin_mass_invite_path, method: :get %>

    <div class="mini_paginator top_paginator">
      <%== pagy_nav @pagy %>
    </div>

    <div class="box">
      <h2>
        <%= params[:filter_by] == 'archived' ? 'Archived' : 'Active' %>
        mass invites
      </h2>
      <table>
        <thead>
          <tr>
            <th>Name</th>
            <th>Created</th>
            <th>Users count</th>
            <th>Link to invite url</th>
          </tr>
        </thead>
        <tbody>
          <%= render @mass_invites %>
        </tbody>
      </table>
    </div>

    <div class="mini_paginator bottom_paginator">
      <%== pagy_nav @pagy %>
    </div>
  </div>
</div>

app/views/admin/mass_invites/new.html.erb
<div id="admin_columns">
  <div class="admin_column_left box">
    <h2>Admin</h2>
    <%= render partial: 'admin/navigation' %>
  </div>
  <div class="admin_column_right">
    <div class="admin_column_right_inner box">
      <h2>Create a new mass invite</h2>
      <%= render 'form' %>
    </div>
  </div>
</div>