config/routes.rb
require 'sidekiq/web'
require 'moderator_constraint'

Rails.application.routes.draw do
  # mount Sidekiq::Web => '/sidekiq', :constraints => ModeratorConstraint.new

  namespace :admin do
    get 'possibly_deleted_user/:id', :to => 'users#show', as: 'possibly_deleted_user'

    resources :account_requests, path: 'account_requests/(:filter_by)' do
      member do
        put :approve
        put :deny
      end
    end
    resources :users, path: 'users/(:filter_by)', only: [:index] do
      member do
        put :delete
        put :restore
        put :unspam
        put :spam
        put :mark_all_users_with_ip_as_spam
      end
    end
    resources :comments, path: 'comments/(:filter_by)', only: [:index] do
       member do
        put :unspam
        put :spam
      end
    end
    resources :assets, path: 'assets/(:filter_by)', only: [:index] do
      member do
        put :unspam
        put :spam
        put :delete
        put :restore
      end
    end
    resources :mass_invites, param: :token
  end

  get '/get_an_account', :to => 'account_requests#new'
  resources 'account_requests', only: :create

  post '/get_an_account', :to => 'account_requests#create'
  get '/upload', :to => 'assets#new'
  post '/listens', :to => 'listens#create', as: 'register_listen'
  get '/new_album', :to => 'playlists#new'
  get '/favorites', :to => 'playlists#favorites'
  get '/login', :to => 'user_sessions#new', :as => 'login'
  get '/login/sso', :to => 'discourse_sso#sso'
  get '/logout', :to => 'user_sessions#destroy', as: 'logout', via: [:get, :post]
  get '/notifications/subscribe' => 'notifications#subscribe'
  get '/notifications/unsubscribe' => 'notifications#unsubscribe'

  get '/follow/:login' => 'following#follow', as: :follow
  get '/unfollow/:login' => 'following#unfollow', as: :unfollow

  # admin stuff
  get 'admin' => 'admin#index'
  get 'secretz' => 'admin#secretz'
  put 'toggle_theme' => 'pages#toggle_theme'

  get '404', to: "pages#four_oh_four"
  get 'raise_error', to: 'pages#raise_error'
  get '500', to: "pages#error"
  get 'error', to: "pages#error"
  get 'ok', to: "pages#ok"

  # one-off pages
  get 'events/rpmchallenge' => 'pages#rpm_challenge'
  get 'events/24houralbum' =>  'pages#twentyfour'

  resources :password_resets, :comments, :user_sessions, :groups

  get 'about/' => 'pages#about'
  get 'about/why-i-built-alonetone' => 'pages#why'
  %w(about press stats ok help privacy faq donate).each do |action|
    get "about/#{action}", to: "pages##{action}"
  end

  get 'signup', to: 'users#new'
  get '/activate/:perishable_token', to: 'users#activate'

  get 'radio' =>'assets#radio', :as => 'radio_home'
  get 'radio/:source' => 'assets#radio', :as => 'radio_source_home'
  get 'radio/:source/:items' => 'assets#radio', :as => 'radio'

  # top 40
  get  '/top/:top' => 'assets#top', :as => 'top'

  get 'comments' => 'comments#index', :as => 'all_comments'
  get 'playlists' => 'playlists#all', :as => 'all_playlists'

  put 'toggle_favorite' => 'users#toggle_favorite'

  match 'search' => 'search#index', via: [:post]
  match 'search/:query' => 'search#index', :as => 'search_query', via: [:get, :post]

  root :to => 'assets#latest'

  get '/users', to: redirect('/users/by/last_seen/1')
  resources :users

  # unless we have the /by/ in the route, we end up in conflict with the resource route
  get '/users/by/:sort/(:page)' => 'users#index', :as => 'sorted_users'

  get '/invite/:mass_invite_token', to: 'mass_invites_users#new', as: 'mass_invite'
  resources :mass_invites, param: :token, only: [] do
    resource :users, only: %i[new create show], controller: :mass_invites_users
  end

  get ':login/history' => 'listens#index', :as => 'listens'
  get ':login/comments' => 'comments#index', :as => 'user_comments'
  get '/:login/toggle-follow' => 'following#toggle_follow', as: :toggle_follow
  put '/:login/toggle-follow' => 'following#toggle_follow', as: :put_toggle_follow

  get ':id' => 'users#show', :as => "user_home" # DEPRECATED (duplicate)
  resources :users, :path => "/" do
    member do
      post :attach_pic
      get :sudo
      put :toggle_setting
    end
    resource 'profile'
    resources 'tracks', controller: :assets do
      member do
        get :share
        get :stats
      end
      collection do
        get  :latest
        post :search
        get  :mass_edit
      end
      resources :comments,  only: [:create, :destroy]
    end
    resources :favorites
    resources :playlists do
      collection do
        get :latest
        post :sort
        get :sort
      end
      member do
        post :attach_pic
        get  :remove_track
        post :set_playlist_title
        post :set_playlist_description
        post :sort_tracks
        post :add_track
      end
      resources :comments
    end
    get '/playlists/:id/:asset_id', :to => 'playlists#show', as: 'show_track_in_playlist'
  end
end

app/views/admin/_navigation.html.erb
<ul class="admin_nav">

  <%= navigation_item "Account Requests <span>#{AccountRequest.count}</span>", admin_account_requests_path %>
  <ul>
    <%= navigation_item "Waiting Musicians <span>#{AccountRequest.candidates.count }</span>", admin_account_requests_path({filter_by: :candidates}) %>
    <%= navigation_item "Waiting Spammers <span>#{AccountRequest.spammers.count }</span>", admin_account_requests_path({filter_by: :spammers}) %>
    <%= navigation_item "Claimed <span>#{AccountRequest.claimed.count }</span>", admin_account_requests_path({filter_by: :claimed}) %>
    <%= navigation_item "Approved <span>#{AccountRequest.approved.count }</span>", admin_account_requests_path({filter_by: :approved}) %>
    <%= navigation_item "Denied <span>#{AccountRequest.denied.count }</span>", admin_account_requests_path({filter_by: :denied}) %>
  </ul>

  <%= navigation_item "All Users <span>#{User.with_deleted.count}</span>", admin_users_path %>
  <ul>
    <%= navigation_item "Valid <span>#{User.filter_by('not_spam').count}</span>", admin_users_path({filter_by: :not_spam}) %>
    <%= navigation_item "Mass Invited <span>#{User.filter_by('invited').count}</span>", admin_users_path({filter_by: :invited}) %>
    <%= navigation_item "Spam <span>#{User.filter_by('is_spam').count}</span>", admin_users_path({filter_by: :is_spam}) %>
    <%= navigation_item "Spammed Musicians <span>#{User.filter_by('spam_musicians').count}</span>", admin_users_path({filter_by: :spam_musicians}) %>
    <%= navigation_item "Deleted (Not Spam) <span>#{User.filter_by('deleted').count}</span>", admin_users_path({filter_by: :deleted}) %>
  </ul>

  <%= navigation_item "Mass Invites <span>#{MassInvite.active.count}</span>",  admin_mass_invites_path({ filter_by: 'active' }) %>
  <ul>
    <%= navigation_item "Archived <span>#{MassInvite.archived.count}</span>",  admin_mass_invites_path({ filter_by: 'archived' }) %>
  </ul>

  <%= navigation_item "All Tracks <span>#{Asset.with_deleted.count}</span>", admin_assets_path %>
  <ul>
    <%= navigation_item "Not Spam <span>#{Asset.count}</span>", admin_assets_path({filter_by: :not_spam}) %>
    <%= navigation_item "Deleted Spam <span>#{Asset.with_deleted.where(is_spam: true).count}</span>", admin_assets_path({filter_by: :is_spam}) %>
    <%= navigation_item "Deleted (Not Spam) <span>#{Asset.only_deleted.where(is_spam: false).count}</span>", admin_assets_path({filter_by: :deleted}) %>
  </ul>

  <%= navigation_item 'All Comments',  admin_comments_path %>
  <ul>
    <%= navigation_item 'Spam',  admin_comments_path({filter_by: {is_spam: true}}) %>
    <%= navigation_item 'Not Spam', admin_comments_path({filter_by: {is_spam: false}}) %>
  </ul>

  <li><%= link_to "Secretz", "/secretz" %></li>
  <li><%= link_to "Akismet Stats", "https://akismet.com/web/1.0/user-stats.php?blog=alonetone.com&api_key=#{Rails.configuration.alonetone.rakismet_key}"%></li>
  <li><%= link_to "Postmark Stats", "https://account.postmarkapp.com/servers/2804035/streams" %></li>
  <li><%= link_to "Job Status", "/sidekiq" %></li>
</ul>

app/views/admin/index.html.erb
<div id="admin_columns">
  <div class="admin_column_left box">
    <h2>Admin</h2>
    <%= render partial: 'admin/navigation' %>
  </div>
</div>

app/views/admin/secretz.html.erb
<div id="admin_columns">
  <div class="admin_column_left box">
    <h2>Admin</h2>
    <%= render partial: 'admin/navigation' %>
  </div>

  <div class="admin_column_right">

    <div class="box">

      <h2 class="table">Users that share the same IP</h2>
      <div class="static_content secretz">
        <table id="listens_by_ip" class="statstable">
          <thead>
            <tr>
              <th>Country</th>
              <th>IP</th>
              <th>Users</th>
              <th>Examples</th>
            </tr>
          </thead>
          <tbody>
          <% @same_ip_users.each do |ip, count| %>
            <% users = User.where(last_login_ip: ip).limit(5) %>
            <tr class>
              <td>
                  <%= image_tag('http://api.hostip.info/flag.php?ip='+ip, size: '20x20', style: 'float:left; clear:none;opacity:0.4;') if ip %>
              </td>
              <td>
                  <%= link_to(ip, 'http://www.botsvsbrowsers.com/ip/'+ip) if ip %>
              </td>
              <td>
                <%= count %>
              </td>
              <td>
                  <%= users.collect{|u| link_to(u.name, user_path(u.login))}.join(" ").html_safe %>
              </td>
            </tr>
          <% end %>
          </tbody>
        </table>
      </div>

      <h2 class="table">IPs that love to listen</h2>
      <div class="static_content secretz">
        <table id="listens_by_ip" class="statstable">
          <thead>
            <tr>
              <th>Country</th>
              <th>IP</th>
              <th>Count</th>
              <th>User?</th>
            </tr>
          </thead>
          <tbody>
          <% @ip_listens.each do |ip, count| %>
            <tr class>
              <td>
                  <%= image_tag('http://api.hostip.info/flag.php?ip='+ip, size: '20x20', style: 'float:left; clear:none;opacity:0.4;')%>
              </td>
              <td>
                  <%= link_to ip, 'http://www.botsvsbrowsers.com/ip/'+ip %>
              </td>
              <td>
                <%= count %>
              </td>
              <td class="uploader">
                  <% user = User.where(last_login_ip: ip) %>
                  <%= user.name if user %>
              </td>
              <td></td>
            </tr>
          <% end %>
          </tbody>
        </table>
      </div>

      <h2 class="table">Tracks that love to get played (last 30 days)</h2>
      <div class="static_content secretz">
      <table id="listens_by_track" class="statstable">
        <thead>
          <tr>
            <th>Track</th>
            <th>Count</th>
            <th>Uploader</th>
            <th>mp3 title</th>
            <th>mp3 artist</th>
          </tr>
        </thead>

        <tbody>
        <% @track_listens.each do |track, count| %>
          <tr class>
            <td><%= link_to track.name, user_track_path(track.user.login, track.permalink) %></td>
            <td><%= count %></td>
            <td class="uploader">
              <%= user_image(track.user, variant: :small_avatar) %>
              <%= track.user.name %>
            </td>
            <td><%= track.title %></td>
            <td><%= track.artist %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
      </div>

      <h2 class="table">All time tracks by play count</h2>
      <div class="static_content secretz">
        <table id="listens_by_track" class="statstable">
          <thead>
            <tr>
              <th>Track</th>
              <th>Count</th>
              <th>Uploader</th>
              <th>mp3 title</th>
              <th>mp3 artist</th>
            </tr>
          </thead>

          <tbody>
          <% @all_time_track_listens.each do |track| %>
            <tr class>
              <td><%= link_to track.name, user_track_path(track.user.login, track.permalink) %></td>
              <td><%= track.listens_count %></td>
              <td class="uploader">
                <%= user_image(track.user, variant: :small_avatar) %>
                <%= track.user.name %>
              </td>
              <td><%= track.title %></td>
              <td><%= track.artist %></td>
            </tr>
          <% end %>
          </tbody>
        </table>
      </div>

      <h2 class="table">All time tracks by play count</h2>
      <div class="static_content secretz">
        <table id="listens_by_track" class="statstable">
          <thead>
            <tr>
              <th>Track</th>
              <th>Count</th>
              <th>Uploader</th>
              <th>mp3 title</th>
              <th>mp3 artist</th>
            </tr>
          </thead>

          <tbody>
          <% @all_time_track_listens.each do |track| %>
            <tr class>
              <td><%= link_to track.name, user_track_path(track.user.login, track.permalink) %></td>
              <td><%= track.listens_count %></td>
              <td class="uploader">
                <%= user_image(track.user, variant: :small_avatar) %>
                <%= track.user.name %>
              </td>
              <td><%= track.title %></td>
              <td><%= track.artist %></td>
            </tr>
          <% end %>
          </tbody>
        </table>
      </div>

      <h2 class="table">Top Bandwidth Users</h2>
      <div class="static_content secretz">
        <table id="listens_by_track" class="statstable">
          <thead>
            <tr>
              <th>User</th>
              <th>Track Count</th>
              <th>GB used</th>
              <th>Cost</th>
            </tr>
          </thead>

          <tbody>
          <% @expensive_users.each do |user| %>
            <tr class>
              <td class="uploader">
                <%= user_image(user, variant: :small_avatar) %>
                <%= link_to user.name, user_home_path(user.login) %></td>
              <td><%= user.assets_count %></td>
              <td>
                ~<%= user.bandwidth_used %> GB
              </td>
              <td><%= user.total_bandwidth_cost %></td>
            </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </Put div>
</div>