config/routes.rb
require 'sidekiq/web'
require 'moderator_constraint'

Rails.application.routes.draw do
  # mount Sidekiq::Web => '/sidekiq', :constraints => ModeratorConstraint.new

  namespace :admin do
    get 'possibly_deleted_user/:id', :to => 'users#show', as: 'possibly_deleted_user'

    resources :account_requests, path: 'account_requests/(:filter_by)' do
      member do
        put :approve
        put :deny
      end
    end
    resources :users, path: 'users/(:filter_by)', only: [:index] do
      member do
        put :delete
        put :restore
        put :unspam
        put :spam
        put :mark_all_users_with_ip_as_spam
      end
    end
    resources :comments, path: 'comments/(:filter_by)', only: [:index] do
       member do
        put :unspam
        put :spam
      end
    end
    resources :assets, path: 'assets/(:filter_by)', only: [:index] do
      member do
        put :unspam
        put :spam
        put :delete
        put :restore
      end
    end
    resources :mass_invites, param: :token
  end

  get '/get_an_account', :to => 'account_requests#new'
  resources 'account_requests', only: :create

  post '/get_an_account', :to => 'account_requests#create'
  get '/upload', :to => 'assets#new'
  post '/listens', :to => 'listens#create', as: 'register_listen'
  get '/new_album', :to => 'playlists#new'
  get '/favorites', :to => 'playlists#favorites'
  get '/login', :to => 'user_sessions#new', :as => 'login'
  get '/login/sso', :to => 'discourse_sso#sso'
  get '/logout', :to => 'user_sessions#destroy', as: 'logout', via: [:get, :post]
  get '/notifications/subscribe' => 'notifications#subscribe'
  get '/notifications/unsubscribe' => 'notifications#unsubscribe'

  get '/follow/:login' => 'following#follow', as: :follow
  get '/unfollow/:login' => 'following#unfollow', as: :unfollow

  # admin stuff
  get 'admin' => 'admin#index'
  get 'secretz' => 'admin#secretz'
  put 'toggle_theme' => 'pages#toggle_theme'

  get '404', to: "pages#four_oh_four"
  get 'raise_error', to: 'pages#raise_error'
  get '500', to: "pages#error"
  get 'error', to: "pages#error"
  get 'ok', to: "pages#ok"

  # one-off pages
  get 'events/rpmchallenge' => 'pages#rpm_challenge'
  get 'events/24houralbum' =>  'pages#twentyfour'

  resources :password_resets, :comments, :user_sessions, :groups

  get 'about/' => 'pages#about'
  get 'about/why-i-built-alonetone' => 'pages#why'
  %w(about press stats ok help privacy faq donate).each do |action|
    get "about/#{action}", to: "pages##{action}"
  end

  get 'signup', to: 'users#new'
  get '/activate/:perishable_token', to: 'users#activate'

  get 'radio' =>'assets#radio', :as => 'radio_home'
  get 'radio/:source' => 'assets#radio', :as => 'radio_source_home'
  get 'radio/:source/:items' => 'assets#radio', :as => 'radio'

  # top 40
  get  '/top/:top' => 'assets#top', :as => 'top'

  get 'comments' => 'comments#index', :as => 'all_comments'
  get 'playlists' => 'playlists#all', :as => 'all_playlists'

  put 'toggle_favorite' => 'users#toggle_favorite'

  match 'search' => 'search#index', via: [:post]
  match 'search/:query' => 'search#index', :as => 'search_query', via: [:get, :post]

  root :to => 'assets#latest'

  get '/users', to: redirect('/users/by/last_seen/1')
  resources :users

  # unless we have the /by/ in the route, we end up in conflict with the resource route
  get '/users/by/:sort/(:page)' => 'users#index', :as => 'sorted_users'

  get '/invite/:mass_invite_token', to: 'mass_invites_users#new', as: 'mass_invite'
  resources :mass_invites, param: :token, only: [] do
    resource :users, only: %i[new create show], controller: :mass_invites_users
  end

  get ':login/history' => 'listens#index', :as => 'listens'
  get ':login/comments' => 'comments#index', :as => 'user_comments'
  get '/:login/toggle-follow' => 'following#toggle_follow', as: :toggle_follow
  put '/:login/toggle-follow' => 'following#toggle_follow', as: :put_toggle_follow

  get ':id' => 'users#show', :as => "user_home" # DEPRECATED (duplicate)
  resources :users, :path => "/" do
    member do
      post :attach_pic
      get :sudo
      put :toggle_setting
    end
    resource 'profile'
    resources 'tracks', controller: :assets do
      member do
        get :share
        get :stats
      end
      collection do
        get  :latest
        post :search
        get  :mass_edit
      end
      resources :comments,  only: [:create, :destroy]
    end
    resources :favorites
    resources :playlists do
      collection do
        get :latest
        post :sort
        get :sort
      end
      member do
        post :attach_pic
        get  :remove_track
        post :set_playlist_title
        post :set_playlist_description
        post :sort_tracks
        post :add_track
      end
      resources :comments
    end
    get '/playlists/:id/:asset_id', :to => 'playlists#show', as: 'show_track_in_playlist'
  end
end

app/views/shared/_analytics.html.erb
<% if tracking_id = Rails.configuration.alonetone.google_analytics_tracking_id %>
  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=<%= tracking_id %>"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', '<%= tracking_id %>');
  </script>
<% end %>

app/views/shared/_asset.html.erb
<% if @playlist %>
<turbo-frame id="playlist-track" target="_top" data-turbo-action="advance">
<div class="track_content" data-controller="big-play" data-playlist-target="track" data-action="
   track:whileLoading@document->big-play#whileLoading
   track:pause@document->big-play#pause
   track:play@document->big-play#play
   track:playing@document->big-play#playing
   track:ended@document->big-play#stop
   track:seeked@document->big-play#seeked
	 playlist-track-playback:updateState@window->big-play#updateState
   track:whilePlaying@document->big-play#whilePlaying"
	 data-big-play-track-id-value="<%= @track.id %>">

<% else %>
	<% content_for :open_graph do %>
	  <meta property="og:url" content="<%= request.url %>" />
	  <meta property="og:type" content="music.song" />
	  <meta property="og:title" content="<%= @asset.title %>" />
	  <meta property="og:description" content="A track by <%= @user.name %>" />
	  <meta property="og:image" content="<%= user_avatar_url(@user, variant: :large_avatar) %>" />
	  <meta property="music.musician" content="<%= user_home_path(@user) %>">
	<% end %>

<div class="track_content stitches_track "
  data-controller="big-play single-playback"
  data-action="
    track:play->big-play#play
    track:playing->big-play#playing
    track:pause->big-play#pause
    track:ended->big-play#stop
    track:whileLoading->big-play#whileLoading
    track:whilePlaying->big-play#whilePlaying
    track:registerListen->single-playback#registerListen
    track:seeked->big-play#seeked
    big-play:seek->single-playback#seek"
  data-single-playback-id="<%= @asset.id %>">
  <%= render partial: 'shared/back_to_artist' %>
<% end %>

  <%= render partial: 'assets/big_player' %>

  <div class="track_post">
    <h1><%= @asset.name %></h1>
    <% unless @playlist %>
      <h3><%= link_to @asset.user.name, user_home_path(@asset.user) %></h3>
    <% end %>
    <div class="track_stats">
      <div class="created">Uploaded <%= local_time_ago(@asset.created_at) %>.</div>
      <div class="favorites">
        <i class="icon_favs">
          <%== render file: svg_path('svg/icon_favorite_inverted.svg') %>
        </i>
        <%= @asset.favorites_count %>
      </div>
      <div class="plays">
        <i class="icon_plays">
          <%== render file: svg_path('svg/icon_play_inverted.svg') %>
        </i>
        <%= @asset.listens_count %>
      </div>

    </div>

    <%= format_track_description(@asset.description) %>

    <div>
      <%= markdown(@asset.credits) if @asset.credits.present? %>
    </div>

    <div class= "edit_links_and_favorite">
      <% if logged_in? %>
        <div class="track_favorite">
        <%= button_to toggle_favorite_path(asset_id: @asset.id), class: 'add_to_favorites',
            method: :put, data: {controller: 'favorite', action: 'favorite#toggle', 'favorite-id-value': @asset.id} do %>
            Favorite <%== render file: svg_path('svg/animation_heart.svg') %>
        <% end %>
        </div>
      <% end %>

      <% if @asset.audio_file.attached? %>
      <div class="download_link">
        <a href="<%= media_url(@asset) %>" download="<%= @asset.audio_file.filename %>">
          Download <%== render file: svg_path('svg/song_download.svg') %>
        </a>
      </div>
      <% end %>

      <div class="edit_links">
        <% if authorized? %>
          <%= link_to("Edit", edit_user_track_path(@user, @asset), class: "edit_link") %>
        <% end %>

        <% if moderator? %>
          <% if @asset.is_spam? %>
            <%= link_to "Unspam", unspam_admin_asset_path(@asset.id), method: :put, class: "edit_link" %>
          <% else %>
            <%= link_to "Spam", spam_admin_asset_path(@asset.id), method: :put, class: "edit_link" %>
          <% end %>
        <% end %>
      </div>

    </div>

  </div>

  <%= render partial: 'assets/comment', locals: { asset: @asset } if can_comment_on?(@asset) %>
  <%= render partial: 'shared/comments' if @comments.present? %>

  <% if @listeners.present? %>
  <div class="track_social">
  <h3>Recent Listeners</h3>
    <div class='recent_listeners'>
    <%= render partial: 'shared/users_to_edge', locals: {users: @listeners } %>
    </div>
  </div>
  <% end %>

  <% if @favoriters.present? %>
  <div class="track_social">
  <h3>Favorited By</h3>
    <div class='favoriters'>
    <%= render partial: 'shared/users_to_edge', locals: {users: @favoriters } %>
    </div>
  </div>
  <% end %>
</div>
</turbo-frame>

app/views/shared/_back_to_artist.html.erb
<%= link_to user_home_path(@user), class: 'back_to_artist_link' do %>
  <div class="caret">
    <i class="icon_caret">
      <%== render file: svg_path('svg/icon_caret.svg') %>
    </i>
  </div>
  <div class="text">
    Back to <span><%= @user.name %></span>'s profile
  </div>
<% end %>

app/views/shared/_comment.html.erb
<% if should_display_track_with_comment? %>
  <%= render(partial: 'assets/asset', layout: 'assets/normal_playback',
    locals: { asset: comment.commentable }) if comment.commentable_type == "Asset" %>
<% end %>

<%= div_for comment do %>
  <div class="comment_user">
    <%= user_image_link(comment.commenter, variant: :small_avatar) %>
	</div>

	<div class="comment_right">
		<div class="comment_user_text">
			<%= comment.commenter ? (link_to comment.commenter.name, user_home_path(comment.commenter)) : 'Guest' %>
			<% if logged_in? %>
		<span class="comment_ip">
			(<%= comment.remote_ip %>)
		</span>
		<% end %>
		said <%= local_time_ago(comment.created_at) %>
		</div>

		<div class="comment_body">
			<p>
				<%= strip_tags(comment.body) %>
			</p>
		<% if comment.private %>
			<div class="private_message">private message</div>
		<% end %>

		<% if authorized_for_comment(comment) -%>
			<div class="comment_controls">
					<% if comment.is_spam? %>
						<%= link_to 'un-spam', unspam_admin_comment_path(comment),  data: { turbo_method: :put, turbo_confirm: 'This will make the comment public. Are you sure?'} %>
					<% else %>
						<%= link_to 'mark as spam', spam_admin_comment_path(comment),  data: { turbo_method: :put, turbo_confirm: 'Are you sure you want to mark this as SPAM? This will make it harder for the user who posted this comment to post again'}%>
					<% end %>
				<%= link_to 'delete', comment_path(comment), data: { turbo_method: :delete, turbo_confirm: 'Are you sure you want to delete this comment?'} %>
			</div>
			<% end %>
		</div>
	</div>

	<div class="clear">
	</div>
<% end if comment && (!comment.private? || authorized_for_comment(comment))%>

app/views/shared/_errors.html.erb
<% if errors.any? %>
  <div id="error_explanation">
    <h3>
    <% if errors.size == 1 %>
      One minor thing looks off:
    <% else %>
      Please fix the following:
    <% end %>
    </h3>
    <ol>
    <% errors.each do |error| %>
      <li><%= error.full_message %></li>
    <% end %>
    </ol>
  </div>
<% end %>

app/views/shared/_favorite.html.erb
  <div class="asset" data-controller="normal-playback">
    <%= render partial: 'assets/asset_white', layout: 'normal_playback',
      locals: {asset: favorite.asset, favorite: favorite } %>
  </div>

app/views/shared/_flash.html.erb
<div class="flash">
  <%= flash.html_safe %>
</div>

app/views/shared/_header.html.erb
  <div class="page_container header_inner">

    <a href="/" title="home" class="header_logo"></a>

    <%= render partial: 'shared/search' %>

    <% if logged_in? %>
      <div class="user_dropdown" data-controller="user-dropdown"
        data-action="keydown@window->user-dropdown#handleEvent">

        <%= link_to '#', class: 'profile_link', data: {action: "user-dropdown#open" } do %>
          <%= user_image(current_user, variant: :small_avatar) %>
        <% end %>

        <div class="user_dropdown_menu" style="display:none;"
          data-user-dropdown-target="menu">

          <div class="user_dropdown_menu_header" data-user-dropdown-target="header">
            <%= truncate current_user.name, length: 24 %>
            <%= user_image(current_user, variant: :small_avatar) %>
          </div>

          <ul class="user_dropdown_menu_items">
            <li>
                <%= link_to 'Your Profile', main_app.user_home_path(current_user) %>
                <%= link_to 'Edit', main_app.edit_user_path(current_user), class: 'edit_profile_item' %>
            </li>
            <li><%= link_to 'Upload New Track', main_app.upload_path %></li>
            <li><%= link_to 'Create Album or Playlist', main_app.new_user_playlist_path(current_user) %></li>
          </ul>

          <div class="user_dropdown_menu_bottom_links">
            <a href="#" class="switch_to_theme switch_to_light"
              data-user-dropdown-target="switchToLight"
              data-action="click->user-dropdown#switchToLight"
              style="display: <%= 'none' if light_theme? %>" >
              <div class="switcher_label">DARK</div>
              <div class="switcher_inner"></div>
            </a>
            <a href="#" class="switch_to_theme switch_to_dark"
              data-user-dropdown-target="switchToDark"
              data-action="click->user-dropdown#switchToDark"
              style="display: <%= 'none' if dark_theme? %>" >
              <div class="switcher_inner"></div>
              <div class="switcher_label">LIGHT</div>
            </a>
            <%= link_to 'Log Out', main_app.logout_path, class: 'logout_item', data: { turbolinks: "false" } %>
          </div>

        </div>
      </div>
    <% end %>

  <% unless logged_in? %>
    <%= link_to 'Log in', main_app.login_path, class: 'login_button' %>
  <% end %>
</div>

app/views/shared/_javascript_payload.html.erb
<%= javascript_tag do %>
  window.username = '<%= logged_in? ? current_user.login : "Guest" %>';
  window.userIsAdmin = <%= moderator? ? true : false %>;
  window.userFavorites = <%= (logged_in? ? current_user.favorite_asset_ids : [] ).to_json %>;
  window.showPlayCounts = <%= logged_in? && current_user.settings && (current_user.settings[:display_listen_count] == "true") ? true : false %>;
  window.userPersonalization = '<div>' +
     <% if logged_in? %>
        'Say something, <span class="comment_as_user"><%= escape_javascript(current_user.name)%></span>:'+
     <% else %>
        'Comment as a <span class="comment_as_guest">Guest</span> or <%= link_to 'login', login_path, title: 'login to alonetone' %>:'+
     <% end %>
  '</div>';

<% end %>

app/views/shared/_playlist.html.erb
<%= content_tag_for :li, playlist, data: { 'id': playlist.id }, class: "small_playlists #{'private' unless playlist.published?}" do %>
  <%= link_to user_playlist_path(playlist.user.login, playlist), title: "#{playlist.title}" do %>
    <%= playlist_cover(playlist, variant: :playlist_card) %>
	<% end %>
  <%= link_to(title_and_year_for(playlist), user_playlist_path(playlist.user.login, playlist), class: 'small_playlist_title', title: "#{playlist.title} by #{playlist.user.name}" ) %>
  <div class="small_playlist_user">
    <% unless @user %>
    <span class="by">by</span><%= link_to truncate(playlist.user.name, length: 26), user_home_path(playlist.user) %>
    <% end %>
  </div>
  <div class="private_playlist_padlock"></div>
<% end %>

app/views/shared/_preloads.html.erb
<link rel="preload" href="https://cdn.alonetone.com/fonts/Alright-v2-Normal-Regular-latin1-tnum.woff2" as="font" type="font/woff2" crossorigin>
<link rel="preload" href="https://cdn.alonetone.com/fonts/Alright-v2-Normal-Medium-latin1-tnum.woff2" as="font" type="font/woff2" crossorigin>
<link rel="preload" href="https://cdn.alonetone.com/fonts/Alright-v2-Normal-Bold-latin1-tnum.woff2" as="font" type="font/woff2" crossorigin>
<link rel="preload" href="https://cdn.alonetone.com/fonts/Alright-v2-Normal-Black-latin1-tnum.woff2" as="font" type="font/woff2" crossorigin>

app/views/shared/_user.html.erb
<li>
<%= div_for(user, class: 'user_index') do %>
  <%= link_to(user_home_path(user), class: 'overlay', title: user_summary(user)) do %>
    <%= image_tag(user_avatar_url(user, variant: :card_avatar), class: 'cover') %>
  <% end %>
  <%= link_to user.name, user_home_path(user.login), class: (user.admin? ? "admin name" : 'name') %>
  <span class="details" style="display:none;">
    <%= link_to(pluralize(user.assets_count, 'track'), user_tracks_path(user)) if user.assets_count > 0 %><br/>
    <%= link_to(pluralize(user.playlists_count, 'playlist'), user_playlists_path(user)) if user.playlists_count > 0 %>
    <% if admin? %>
      <%= link_to 'delete', user_path(user), method: :delete, confirm: "This will delete this user entirely, including all #{user.assets_count} tracks and #{user.playlists_count} playlists" %>
    <% end %>
  </span>
<% end %>
</li>

app/views/shared/_users_to_edge.html.erb
<% users.each do |user| %>
  <%= div_for(user, class: 'user_small_avatar') do %>
    <%= user_image_link(user, variant: :small_avatar)%>
  <% end %>
<% end %>

app/views/shared/_welcome_back.html.erb
<div class="flash">
  Welcome back, <%= current_user.name %><br/>
  <div class="flash_stats">
      <% if new_plays = current_user.plays_since_last_session %>
        You have <%= link_to "#{new_plays} new track plays", listens_path(current_user.login) %>
      <% end %>
      <% if new_comments = current_user.comments_since_last_session %>
        <%= new_plays ? ' and ' : 'You have' %>
        <%= link_to "#{new_comments} new comments", user_comments_path(current_user.login) %>
      <% end %>
      <% if new_plays || new_comments %>
        since you last logged in (<%= local_time_ago(current_user.last_session_at) %>)
      <% end %>
  </div>
</div>