config/routes.rb
require 'sidekiq/web'
require 'moderator_constraint'

Rails.application.routes.draw do
  # mount Sidekiq::Web => '/sidekiq', :constraints => ModeratorConstraint.new

  namespace :admin do
    get 'possibly_deleted_user/:id', :to => 'users#show', as: 'possibly_deleted_user'

    resources :account_requests, path: 'account_requests/(:filter_by)' do
      member do
        put :approve
        put :deny
      end
    end
    resources :users, path: 'users/(:filter_by)', only: [:index] do
      member do
        put :delete
        put :restore
        put :unspam
        put :spam
        put :mark_all_users_with_ip_as_spam
      end
    end
    resources :comments, path: 'comments/(:filter_by)', only: [:index] do
       member do
        put :unspam
        put :spam
      end
    end
    resources :assets, path: 'assets/(:filter_by)', only: [:index] do
      member do
        put :unspam
        put :spam
        put :delete
        put :restore
      end
    end
    resources :mass_invites, param: :token
  end

  get '/get_an_account', :to => 'account_requests#new'
  resources 'account_requests', only: :create

  post '/get_an_account', :to => 'account_requests#create'
  get '/upload', :to => 'assets#new'
  post '/listens', :to => 'listens#create', as: 'register_listen'
  get '/new_album', :to => 'playlists#new'
  get '/favorites', :to => 'playlists#favorites'
  get '/login', :to => 'user_sessions#new', :as => 'login'
  get '/login/sso', :to => 'discourse_sso#sso'
  get '/logout', :to => 'user_sessions#destroy', as: 'logout', via: [:get, :post]
  get '/notifications/subscribe' => 'notifications#subscribe'
  get '/notifications/unsubscribe' => 'notifications#unsubscribe'

  get '/follow/:login' => 'following#follow', as: :follow
  get '/unfollow/:login' => 'following#unfollow', as: :unfollow

  # admin stuff
  get 'admin' => 'admin#index'
  get 'secretz' => 'admin#secretz'
  put 'toggle_theme' => 'pages#toggle_theme'

  get '404', to: "pages#four_oh_four"
  get 'raise_error', to: 'pages#raise_error'
  get '500', to: "pages#error"
  get 'error', to: "pages#error"
  get 'ok', to: "pages#ok"

  # one-off pages
  get 'events/rpmchallenge' => 'pages#rpm_challenge'
  get 'events/24houralbum' =>  'pages#twentyfour'

  resources :password_resets, :comments, :user_sessions, :groups

  get 'about/' => 'pages#about'
  get 'about/why-i-built-alonetone' => 'pages#why'
  %w(about press stats ok help privacy faq donate).each do |action|
    get "about/#{action}", to: "pages##{action}"
  end

  get 'signup', to: 'users#new'
  get '/activate/:perishable_token', to: 'users#activate'

  get 'radio' =>'assets#radio', :as => 'radio_home'
  get 'radio/:source' => 'assets#radio', :as => 'radio_source_home'
  get 'radio/:source/:items' => 'assets#radio', :as => 'radio'

  # top 40
  get  '/top/:top' => 'assets#top', :as => 'top'

  get 'comments' => 'comments#index', :as => 'all_comments'
  get 'playlists' => 'playlists#all', :as => 'all_playlists'

  put 'toggle_favorite' => 'users#toggle_favorite'

  match 'search' => 'search#index', via: [:post]
  match 'search/:query' => 'search#index', :as => 'search_query', via: [:get, :post]

  root :to => 'assets#latest'

  get '/users', to: redirect('/users/by/last_seen/1')
  resources :users

  # unless we have the /by/ in the route, we end up in conflict with the resource route
  get '/users/by/:sort/(:page)' => 'users#index', :as => 'sorted_users'

  get '/invite/:mass_invite_token', to: 'mass_invites_users#new', as: 'mass_invite'
  resources :mass_invites, param: :token, only: [] do
    resource :users, only: %i[new create show], controller: :mass_invites_users
  end

  get ':login/history' => 'listens#index', :as => 'listens'
  get ':login/comments' => 'comments#index', :as => 'user_comments'
  get '/:login/toggle-follow' => 'following#toggle_follow', as: :toggle_follow
  put '/:login/toggle-follow' => 'following#toggle_follow', as: :put_toggle_follow

  get ':id' => 'users#show', :as => "user_home" # DEPRECATED (duplicate)
  resources :users, :path => "/" do
    member do
      post :attach_pic
      get :sudo
      put :toggle_setting
    end
    resource 'profile'
    resources 'tracks', controller: :assets do
      member do
        get :share
        get :stats
      end
      collection do
        get  :latest
        post :search
        get  :mass_edit
      end
      resources :comments,  only: [:create, :destroy]
    end
    resources :favorites
    resources :playlists do
      collection do
        get :latest
        post :sort
        get :sort
      end
      member do
        post :attach_pic
        get  :remove_track
        post :set_playlist_title
        post :set_playlist_description
        post :sort_tracks
        post :add_track
      end
      resources :comments
    end
    get '/playlists/:id/:asset_id', :to => 'playlists#show', as: 'show_track_in_playlist'
  end
end

app/controllers/mass_invites_users_controller.rb
# frozen_string_literal: true

class MassInvitesUsersController < ApplicationController
  include UserCreation

  before_action lambda {
    @mass_invite = MassInvite.find_by!(token: params[:mass_invite_token])
    if @mass_invite.archived?
      redirect_to '/get_an_account', flash: { notice: "That invite no longer exists!" }
    end
  }

  def new
    @user = User.new
    @page_title = "You're invited!"
  end

  def create
    @user = @mass_invite.users.new(user_params)
    respond_with_user(@user)
  end

  def show
    redirect_to new_mass_invite_users_url(@mass_invite)
  end

  private

  def user_params
    params.require(:user).permit(:email, :login, :password, :password_confirmation)
  end
end

app/views/mass_invites_users/new.html.erb
<div class="page_container big_form page_container_with_blank_slate_overlapping_content">
  <%= render layout: 'shared/blank_slate', locals: { name: 'jenya', role: 'developer' } do %>
    <p>
      “Welcome, <%= @mass_invite.name %>!
    </p>
    <p>
      You've been invited to create an account on alonetone. <%= link_to "Read more about us", about_path %>.
    </p>
    <p>
      Feel free to share this secret invite link, but please don't post it publicly!”
    </p>
  <% end %>

  <div class="box">
    <h2>Create your alonetone account</h2>
    <%= render partial: 'shared/errors', locals: { errors: @user.errors } %>

    <%= form_with(model: @user, url: mass_invite_users_path(@mass_invite), data: { turbo: false}) do |f| %>
      <div class="form_row">
        <div>
          <%= f.label :email, "Email" %>
          <%= f.text_field :email %>
          <%= inline_form_error(@user.errors[:email]) %>
        </div>
        <div class="field_with_hint_before">
          <%= f.label :login, "Pick a username (no spaces allowed)" %>
          <span>alonetone.com/</span><%= f.text_field :login %>
          <%= inline_form_error(@user.errors[:login]) %>
        </div>
      </div>
      <div class="form_row">
        <div>
          <%= f.label :password, "Password" %>
          <%= f.password_field :password, autocomplete: "new-password" %>
          <%= inline_form_error(@user.errors[:password]) %>

          <%= f.label :password_comfirmation, "Repeat password" %>
          <%= f.password_field :password_confirmation, autocomplete: "new-password" %>
          <%= inline_form_error(@user.errors[:password_confirmation]) %>
        </div>
      </div>
      <div>
        <%= f.submit "Create Account" %>
      </div>
    <% end %>
  </div>
</div>